#!/bin/bash

echo "================================================"
echo "   VISHVAVIRAT SECURITY - WEBSITE COMPLETE!"
echo "================================================"
echo ""
echo "Starting local server..."
echo ""
echo "📁 Main Pages:"
echo "  ✅ http://localhost:8000/index-new.html (Homepage - NEW DESIGN)"
echo "  ✅ http://localhost:8000/about.html (About Us)"
echo "  ✅ http://localhost:8000/services.html (Services Overview)"
echo "  ✅ http://localhost:8000/industries.html (Industries We Serve)"
echo "  ✅ http://localhost:8000/contact.html (Contact Page)"
echo ""
echo "📁 Service Detail Pages:"
echo "  ✅ http://localhost:8000/services/personal-bouncer.html"
echo "  ✅ http://localhost:8000/services/government-security-guard.html"
echo "  ✅ http://localhost:8000/services/driver.html"
echo "  ✅ http://localhost:8000/services/housekeeping.html"
echo "  ✅ http://localhost:8000/services/gardener.html"
echo "  ✅ http://localhost:8000/services/maid.html"
echo ""
echo "📊 Total Pages: 11 (all complete!)"
echo ""
echo "⚠️  NOTE: Images will show as broken - see IMAGE_GUIDE.md"
echo ""
echo "⏹️  Press Ctrl+C to stop server"
echo "================================================"
echo ""

python3 -m http.server 8000
